on: 
  pull_request:
      types: [opened]

jobs:
  snyk_fix_propagate:
    runs-on: ubuntu-latest
    name: Snyk post processing
    steps:
    - name: Fix propagation
      id: snyk-job
      uses: snyk-tech-services/github-actions-snyk-propagate-python-fix@v7
      with:
        myToken: ${{ secrets.ghToken }}
        sourceFilename: requirements3.txt
